# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: cck-ball_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: cck-balls_left_studio
  - board: nice_nano_v2
    shield: cck-ball_left
    artifact-name: cck-ball_left
  - board: nice_nano_v2
    shield: cck-ball_right
    artifact-name: cck-ball_right
  - board: nice_nano_v2
    shield: settings_reset