CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_SMART_ALGORITHM=y
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=8

# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
